services:
  postgres:
    image: postgres:15
    container_name: postgres-demo
    environment:
      POSTGRES_USER: teacher
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: school_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: